### ISSUE TITLE
Broken links to OS docs of Prerequisites Installation 

### ISSUE THREAD

**Issue by vanessametonini** [consul/docs#36] opened 2017-10-11 15:21 UTC
Today I was reading the [Documentation](https://consul_docs.gitbooks.io/docs/content/en/), and when I accessed the [Prerequisites](https://github.com/consul/docs/tree/master/en/getting_started/prerequisites) page I saw that the links for each operating system are pointing to an HTML file and not to the Markdown file that exists in the repository.
It is necessary to fix the broken links. I can fix it, if the PR is welcome. :)

**Comment by bertocq** [comment] 2017-10-11 15:26
Thanks @vanessametonini always PR's are welcome :)

But the problem is that at the README.md file we haven't stated that this documentation is using Gitbooks to be generated, so any markdown file has some quirks to work with it. (We did it on the CONTRIBUTING.md (https://github.com/consul/docs/blob/master/CONTRIBUTING.md#gitbooks) file but maybe on the README.md as well would be a nice idea, what do you think?)

Please read the documentation on the links that the README.md has to both english or spanish languages, for example https://consul_docs.gitbooks.io/docs/content/en/getting_started/prerequisites/ there you'll find any link working as well as a better reading experience :)

**Comment by vanessametonini** [comment] 2017-10-11 15:43
Got it! Sorry for the confusion. 
So, in the [first page](https://www.gitbook.com/book/consul_docs/docs/details) we could fix the link for the Prerequisites to pointing to Gitbook instead of the repo url. What you think?
![screen shot 2017-10-11 at 12 16 26](https://user-images.githubusercontent.com/3089882/31451062-78285154-ae81-11e7-84bd-a52290cba3e8.png)

**Comment by bertocq** [comment] 2017-10-11 18:21
Closed via #37 🎉

**Closed as completed by bertocq** 2017-10-11 18:21 UTC
